### ISSUE TITLE
Use vectorized selection for rioxarray

### ISSUE THREAD

**Issue by spatialthoughts** [kadyb/raster-benchmark#14]
Hi,

I came across this benchmark while comparing rasterstats and rioxarray. Looking into the rioxarray/extract_points.py, I found that it is using iteration instead of much faster vectorized selection. This results in 1000x speedup.

I have opened a PR that shows this improvement. Would be good to test and merge.
https://github.com/kadyb/raster-benchmark/pull/13

**Comment by kadyb** [comment]
I merged this PR, thank you. I have two questions:

1. Can you confirm that this operation after vectorization still uses 1 thread?
2. Can we do something similar for `{rasterio}`?

**Comment by sgillies** [comment]
@kadyb rasterio got a lot faster in 1.3.0 (see https://github.com/rasterio/rasterio/pull/2338) and is even more fast when points are sorted. I haven't compared it to rioxarray.

**Comment by kadyb** [comment]
After updating `{rasterio}` to version 1.3.0 I [see](https://github.com/kadyb/raster-benchmark/commit/c44e99d5555542387a449244e50983c3be7c8a73) the change from 18.17 s to 15.29 s for unsorted points.

BTW: @sgillies, could you check issue #10?

**Comment by spatialthoughts** [comment]
@kadyb Responses below

1. The dask backend is not enabled so it should use single process as before. I verified the resource use and saw a single process for both old and new code.
2. I am not aware of anything faster than rasterio.sample.

**Comment by kadyb** [comment]
I just updated the benchmark. The change for `{rioxarray}` is from 69.7 to 0.08 s for ~68k points. So it looks like `{rioxarray}` and `{terra}` are the two fastest packages. In the next iteration I will add more points to the tests to make the differences more visable. Thanks again for the suggestions!
